### ISSUE TITLE
Backend: Set up the Django Rest Framework backbone and create a CRUD API for Events

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#111]
**Description** 

In deciding our tech stack, we have chosen Django as our backend framework. To quickly get started with backend development we need to set up a baseline Django application, configure with DRF (Django Rest Framework) and also create a CRUD API for **Events** to give people an example for writing APIs.

**Files**

A natural place for the app to live is **/code/backend/**. under the main folder of our repository.

**Tasks**

- [x] Set up the directory structure and create the Django project
- [x] Install and configure the Django Rest Framework to create RESTful APIs
- [x] Create an Events app and a CRUD API for interacting with Events

**Comment by kerimoglutolga** [comment]
Done! Pull request for the changes: https://github.com/bounswe/2021SpringGroup4/pull/110

Here are the updates and general information to get started for backend people:

The backend development branch lives in **backend-main**. No production branch as of yet. To work on any changes, branch out from it with naming in the format **'backend-<-what-you-are-working-on->'.** 

The Django project lives under **/code/backend/**. The main application is called **core**.  We will adopt the convention that for any subapp with an accompanying RESTful API, the API will live in a seperate folder named <_appname_>_api. For example the models and other related code for the events live under **events** folder while the API lives under **events_api**.

In model creation, is it advised to stick to our [class diagram structure](https://github.com/bounswe/2021SpringGroup4/wiki/Class-Diagram) .

**What's next?**

- Setting up API documentation so that frontend and android teams can link up easily.
- Settings up unit tests and automatic workflows on GitHub.
- Configuring the authentication procedures.
