### ISSUE TITLE
Backend: Creating a token-based authentication API and extend Django's base User model to accomodate user profiles

### ISSUE THREAD

**Issue by kerimoglutolga** [bounswe/2021SpringGroup4#117]
**Description**

A core part of our application is to provide users with facilities to register and login to our website in order to create and view events. Ideally, a token-based authentication framework will be employed and configured and endpoints will be set up for login and register operations. Additionally, the base authenticated user model from Django is not sufficient for our needs as the profiles will contain many more information such as an about section and created events of users.

**Files**

The authentication API should live at /code/backend/api/authentication/. 

**Tasks**

- [x] Create an authentication API for users to both register and also obtain tokens to login
- [x] Extend the base User model of Django and configure it for use with authentication
- [x] Provide clear documentation for the API endpoints so that the frontend teams can start using them easily.
