### ISSUE TITLE
Android:Create Event UI

### ISSUE THREAD

**Issue by FatihAkgoz** [bounswe/2021SpringGroup4#123]
## Description:
 UI will be created regarding creating, searching and joining events according to our [requirements](https://github.com/bounswe/2021SpringGroup4/wiki/Software-Requirements-Specification-(SRS)). This is a core feature of our application.
In this process standard android libraries and Kotlin will be used. This issue doesn't include the connection with backend, handling requests etc.
## Tasks:
- [x] Event UI will be designed as homepage of our application. It will show relevant events to the user after successful login.
- [x] Search Bar will be added for finding events.
- [x] UI will be designed for creating events.
- [x] Changes will be applied via a pull request.

**Comment by FatihAkgoz** [comment]
Event UI is ready.

**Comment by eceasslan** [comment]
Added Event Create fragment and UI of the event creation page.
