### ISSUE TITLE
Android: Integration with backend

### ISSUE THREAD

**Issue by FatihAkgoz** [bounswe/2021SpringGroup4#130]
## Description:
Mobile Interface regarding the login, registration and event features will be connected to their respective rest endpoints in the backend.
## Tasks:
- [x] Server will be configured to connect to local docker image.
- [x] Login Endpoint connection will be implemented.
- [x] Registration Endpoint connection will be implemented.
- [x] Create Event Endpoint Endpoint connection will be implemented.
- [x] List Events Endpoint connection will be implemented.
- [x] Search on Events(Basic Single Parameter Search) Endpoint connection will be implemented.
- [x] Changes will be applied to android-main branch via a pull request.

**Comment by eceasslan** [comment]
Installed Docker Desktop and ran docker image. Local connection to backend API is created.

**Comment by eceasslan** [comment]
Login, registration , create event, list event and search event endpoint connections are implemented. A pull request is created to update the android-main with these changes.
