### ISSUE TITLE
Self-Assignment: Study Android Studio, Kotlin and Volley Library

### ISSUE THREAD

**Issue by eceasslan** [bounswe/2021SpringGroup4#161]
### Description:
In order to develop an Android app, I need to know how to use Android Studio, Kotlin and Volley library. So, I found some resources on the internet. This issue will provide the process of learning Android Studio, Kotlin and Volley library.

### Tasks:
- [x] Download and install JDK
- [x] Download and install Android Studio
- [x] Set up Android Emulator
- [x] Learn how to use Android Studio
- [x] Learn how to write codes in Kotlin
- [x] Learn how to use Volley library to access backend

**Comment by eceasslan** [comment]
Found a [video](https://www.youtube.com/watch?v=SXLmr4Qp4OM&list=WL&index=52) on YouTube which is a Kotlin tutorial and also shows how to install JDK, Android Studio and set up Android Emulator. Completed 1st, 2nd, 3rd, 4th and 5th tasks by watching this tutorial.

**Comment by eceasslan** [comment]
Found another [video](https://www.youtube.com/watch?v=0m3uvj68eoY) which is an Android Studio tutorial. The previous tutorial is not enough to create an Android app because activity or layout are not mentioned. Watched this video and improved a better understanding of Android apps.

**Comment by eceasslan** [comment]
This [video](https://www.youtube.com/watch?v=xPi-z3nOcn8&t=3765s) is watched to learn how to use Volley library and send requests to an API. 6th task is completed.
