### ISSUE TITLE
Milestone 2 Features

### ISSUE THREAD

**Issue by FatihAkgoz** [bounswe/2021SpringGroup4#167]
## Description:
 As discussed in the [meeting](https://github.com/bounswe/2021SpringGroup4/issues/166) our Android application will be capable of searching by location, creating new events, and viewing the details of an event to apply or follow the event.

## Tasks:
- [x] Map Function for searching will be added
- [x] Create Event business logic will be implemented
- [x] EventDetailFragment will be implemented

**Comment by FatihAkgoz** [comment]
Milestone is presented with these features working propely.
